function body = GetData(obj,body)
%GetData(obj,body)
%
%     Input:
%       body = (VSOGetDataRequest)
%   
%     Output:
%       body = (VSOGetDataResponse)

% Build up the argument lists.
values = { ...
   body, ...
   };
names = { ...
   'body', ...
   };
types = { ...
   'VSOGetDataRequest', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://virtualsolar.org/VSO/VSOi', ...
    'GetData', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'http://virtualsolar.org/VSO/VSOi#GetData', ...
    soapMessage);
body = parseSoapResponse(response);
