function body = Query(obj,body)
%Query(obj,body)
%
%     Input:
%       body = (QueryRequest)
%   
%     Output:
%       body = (QueryResponse)

% Build up the argument lists.
 values = { ...
    body, ...
    };
%values=body;

 names = { ...
    'body', ...
    };


% names= { ...
%     'provider',  ...
%  'instrument',  ...
%  'time',  ...
%  'wave',  ...
%  'field', ...
%  'pixels'};

types = { ...
   'QueryRequest', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://virtualsolar.org/VSO/VSOi', ...
    'Query', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'http://virtualsolar.org/VSO/VSOi#Query', ...
    soapMessage);
body = parseSoapResponse(response);
