classdef sim_params
    %Class to process and store simulation parameters used and generated by sac/smaug MHD codes
    %   Detailed explanation goes here
    
    properties
        boundary_conditions=[2.0; 2.0; 2.0; 2.0; 2.0; 2.0];
        cosmological_simulation=0;
        current_iteration=0;
        current_time=0;
        dimensionality=3;
        domain_dimensions=[16;16;16];
        domain_left_edge=[0;0; 0.0];
        domain_right_edge=[0; 0; 0];
        eta=0.0;
        adiab=1.0;
        field_ordering=1;
        gamma=1.66666667;
        gravity0=0.0;
        gravity1=0.0;
        gravity2=0.0;
        nu=0.0;
        num_ghost_zones=0;
        refine_by=0;
        unique_identifier='notset';
        
        nw=13; %number of fields
        neqpar=7; %number of equation parameters
         
    end
    
    methods
  
        
        
        
        function newobj=read_params_h5( obj, filename)
            
                  newobj=sim_params;
                  
                  newobj.boundary_conditions=h5readatt(filename,'/simulation_parameters','boundary_conditions');                 
                  newobj.cosmological_simulation =h5readatt(filename,'/simulation_parameters','cosmological_simulation');
                
                  newobj.current_iteration=h5readatt(filename,'/simulation_parameters','current_iteration');
                  newobj.current_time =h5readatt(filename,'/simulation_parameters','current_time');
                  newobj.dimensionality =h5readatt(filename,'/simulation_parameters','dimensionality');

                  newobj.domain_dimensions=h5readatt(filename,'/simulation_parameters','domain_dimensions');

                   newobj.domain_left_edge =h5readatt(filename,'/simulation_parameters','domain_left_edge');
                   newobj.domain_right_edge =h5readatt(filename,'/simulation_parameters','domain_right_edge');

                   newobj.eta =h5readatt(filename,'/simulation_parameters','eta');
                   newobj.field_ordering =h5readatt(filename,'/simulation_parameters','field_ordering');
                 
                   newobj.gamma =h5readatt(filename,'/simulation_parameters','gamma');
                    newobj.adiab =h5readatt(filename,'/simulation_parameters','adiab');
                  newobj.gravity0=h5readatt(filename,'/simulation_parameters','gravity0');
                  newobj.gravity1=h5readatt(filename,'/simulation_parameters','gravity1');
                  newobj.gravity2=h5readatt(filename,'/simulation_parameters','gravity2');
                  
                   newobj.nu =h5readatt(filename,'/simulation_parameters','nu');
                   newobj.num_ghost_zones =h5readatt(filename,'/simulation_parameters','num_ghost_zones');
 
                   newobj.refine_by =h5readatt(filename,'/simulation_parameters','refine_by');
                   c=h5readatt(filename,'/simulation_parameters','unique_identifier');
                   newobj.unique_identifier = c{1};
                 
                   
                   
        end
           
        
              function write_params_h5( obj, filename)
            
                  
                  
                  h5writeatt(filename,'/simulation_parameters/','boundary_conditions',obj.boundary_conditions);                 
                  h5writeatt(filename,'/simulation_parameters/','cosmological_simulation',obj.cosmological_simulation);
                
                  h5writeatt(filename,'/simulation_parameters','current_iteration',obj.current_iteration);
                  h5writeatt(filename,'/simulation_parameters','current_time',obj.current_time );
                  h5writeatt(filename,'/simulation_parameters','dimensionality',obj.dimensionality );

                  h5writeatt(filename,'/simulation_parameters','domain_dimensions',obj.domain_dimensions);

                   h5writeatt(filename,'/simulation_parameters','domain_left_edge',obj.domain_left_edge );
                   h5writeatt(filename,'/simulation_parameters','domain_right_edge',obj.domain_right_edge );

                   h5writeatt(filename,'/simulation_parameters','eta',obj.eta );
                   h5writeatt(filename,'/simulation_parameters','field_ordering',obj.field_ordering );
                 
                   h5writeatt(filename,'/simulation_parameters','gamma',obj.gamma );
                    h5writeatt(filename,'/simulation_parameters','adiab',obj.adiab );
                  h5writeatt(filename,'/simulation_parameters','gravity0',obj.gravity0);
                  h5writeatt(filename,'/simulation_parameters','gravity1',obj.gravity1);
                  h5writeatt(filename,'/simulation_parameters','gravity2',obj.gravity2);
                  
                  h5writeatt(filename,'/simulation_parameters','nu', obj.nu );
                  h5writeatt(filename,'/simulation_parameters','num_ghost_zones', obj.num_ghost_zones );
 
                   h5writeatt(filename,'/simulation_parameters','refine_by',obj.refine_by );
                  h5writeatt(filename,'/simulation_parameters','unique_identifier', obj.unique_identifier );
                 
                   
                   
              end  
 
           
              
                     function newobj=get_simparams_h5( obj, filename)
            
                  
                              gdfinfo=h5info(filename);
                                newobj=sim_params;
                                newobj.cosmological_simulation=gdfinfo.Groups(5).Attributes(1).Value;
                                newobj.boundary_conditions=gdfinfo.Groups(5).Attributes(2).Value;
                                newobj.current_iteration=gdfinfo.Groups(5).Attributes(3).Value;
                                newobj.current_time=gdfinfo.Groups(5).Attributes(4).Value;
                                newobj.dimensionality=gdfinfo.Groups(5).Attributes(5).Value;
                                newobj.domain_dimensions=gdfinfo.Groups(5).Attributes(6).Value;
                                newobj.domain_left_edge=gdfinfo.Groups(5).Attributes(7).Value;
                                newobj.domain_right_edge=gdfinfo.Groups(5).Attributes(8).Value;
                                newobj.eta=gdfinfo.Groups(5).Attributes(9).Value;
                                newobj.field_ordering=gdfinfo.Groups(5).Attributes(10).Value;
                                newobj.gamma=gdfinfo.Groups(5).Attributes(11).Value;
                                newobj.adiab=gdfinfo.Groups(5).Attributes(12).Value;
                                newobj.gravity0=gdfinfo.Groups(5).Attributes(13).Value;
                                newobj.gravity1=gdfinfo.Groups(5).Attributes(14).Value;
                                newobj.gravity2=gdfinfo.Groups(5).Attributes(15).Value;
                                newobj.nu=gdfinfo.Groups(5).Attributes(16).Value;
                                newobj.num_ghost_zones=gdfinfo.Groups(5).Attributes(17).Value;
                                newobj.refine_by=gdfinfo.Groups(5).Attributes(18).Value;
                               c=gdfinfo.Groups(5).Attributes(19).Value;
                                newobj.unique_identifier=c{1};
                                %return newobj;
                   
                   
                      end         
              
              
              
 
    end
    
end

