classdef sim_data
    %Class to process and store data generated by sac/smaug MHD codes
    %   Detailed explanation goes here
 
    
    
    
    properties
           simparams=sim_params;
           gridinfo=sim_gridinfo;
    
            w=zeros(64,16);
    end
    
    methods
         function newobj=read_data_h5( obj, filename)
             newobj=sim_data;
             newobj.simparams=obj.simparams;
             newobj.gridinfo=obj.gridinfo;
             
             t = h5read(filename,'/data/grid_0000000000/density_pert');
             obj.w(:,:,:,2) = h5read(filename,'/data/grid_0000000000/velocity_x');
             obj.w(:,:,:,3) = h5read(filename,'/data/grid_0000000000/velocity_y');
             obj.w(:,:,:,4) = h5read(filename,'/data/grid_0000000000/velocity_z');
             obj.w(:,:,:,5) = h5read(filename,'/data/grid_0000000000/internal_energy_pert');
             obj.w(:,:,:,6) = h5read(filename,'/data/grid_0000000000/mag_field_x_pert');
             obj.w(:,:,:,7) = h5read(filename,'/data/grid_0000000000/mag_field_y_pert');
             obj.w(:,:,:,8) = h5read(filename,'/data/grid_0000000000/mag_field_z_pert');
             obj.w(:,:,:,9) = h5read(filename,'/data/grid_0000000000/internal_energy_bg');
             obj.w(:,:,:,10) = h5read(filename,'/data/grid_0000000000/density_bg');
             obj.w(:,:,:,11) = h5read(filename,'/data/grid_0000000000/mag_field_x_bg');
             obj.w(:,:,:,12) = h5read(filename,'/data/grid_0000000000/mag_field_y_bg');
             obj.w(:,:,:,13) = h5read(filename,'/data/grid_0000000000/mag_field_z_bg');
      
             newobj.w=w;
         end  
         
         function setsim_params(obj, simparams)
             obj.simparams=simparams;
         end
         
         function setsim_gridinfo(obj, gridinfo)
            obj.gridinfo=gridinfo; 
         end
    end
    
end

