classdef sim_gridinfo
    %Class to process and store grid information used and generated by sac/smaug MHD codes
    %   Detailed explanation goes here
    
    properties
        ndimensions=3;
        %grid_dimensions=64*ones(3,1);
        grid_dimensions=[256;128;128];
        grid_left_index=ones(3,1);
        %grid_right_index=0;
        grid_level=0;
        grid_parent_id=0;
        grid_particle_count=0;
        
        data_software='matsac';
        data_software_version='0.1';
        
        
        
    end
    
    methods
        
        function create_groups_h5(obj, filename)
            
           display('testing') 
        end
        
        
        function create_structures_h5( obj, filename)
            
           
                          %create goups
               fid = H5F.create(filename);
            plist = 'H5P_DEFAULT';
            gid = H5G.create(fid,'/simulation_parameters',plist,plist,plist);
            H5G.close(gid);

            %particle types



            %grid_dimensions
            %
            type_id = H5T.copy('H5T_NATIVE_INT64');
            dims = [3];
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(1,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(fid,'grid_dimensions',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);
            %H5F.close(fid);
            %h5disp('myfile.h5');

            %grid_left_index
            %
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            dims = [3];
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(1,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(fid,'grid_left_index',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            dims = [1];
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(1,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(fid,'grid_level',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            dims = [1];
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(1,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(fid,'grid_parent_id',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            dims = [1];
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(1,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(fid,'grid_particle_count',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);




            gid = H5G.create(fid,'/gridded_data_format',plist,plist,plist);


            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(gid,'data_software',type_id,space_id,acpl);
            %H5A.write(attr_id,'H5ML_DEFAULT',10.0)
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(gid,'data_software_version',type_id,space_id,acpl);
            %H5A.write(attr_id,'H5ML_DEFAULT',10.0)
            H5A.close(attr_id);
            H5T.close(type_id);


            H5G.close(gid);

            gid = H5G.create(fid,'/particle_types',plist,plist,plist);
            H5G.close(gid);

            %data
            %create data group

            %i1= int32  simgridinfo.grid_dimensions(1);
            %i2=  (int32) (simgridinfo.grid_dimensions(2));
            %i3=  (int32) (simgridinfo.grid_dimensions(3));
            dim=obj.grid_dimensions;
            i1=double(dim(1));
            i2=double(dim(2));
            i3=double(dim(3));
            dims = [i1 i2 i3];

            plist = 'H5P_DEFAULT';
            dgid = H5G.create(fid,'data',plist,plist,plist);
            gid = H5G.create(dgid,'grid_0000000000',plist,plist,plist);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'density_pert',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'velocity_x',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'velocity_y',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'velocity_z',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'internal_energy_pert',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_x_pert',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_y_pert',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_z_pert',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'internal_energy_bg',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'density_bg',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_x_bg',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_y_bg',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);

            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            h5_dims = fliplr(dims);
            h5_maxdims = h5_dims;
            space_id = H5S.create_simple(3,h5_dims,h5_maxdims);
            dcpl = 'H5P_DEFAULT';
            dset_id = H5D.create(gid,'mag_field_z_bg',type_id,space_id,dcpl);
            H5S.close(space_id);
            H5T.close(type_id);
            H5D.close(dset_id);



            H5G.close(gid);
            H5G.close(dgid);

            %field_types group
            gid = H5G.create(fid,'/field_types',plist,plist,plist);
            
            %field_type group density_bg
            sgid = H5G.create(gid,'/field_types/density_bg',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,17);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','BackgroundDensity')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0.0010000000002);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,25);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{\frac{kg}{m^{3}}}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group density_bg

            %field_type group density_pert
            sgid = H5G.create(gid,'/field_types/density_pert',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,19);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','PerturbationDensity')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0.0010000000002);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,25);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{\frac{kg}{m^{3}}}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group density_pert           
            
            %field_type group internal_energy_bg
            sgid = H5G.create(gid,'/field_types/internal_energy_bg',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,24);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','BackgroundInternalEnergy')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,11);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{Pa}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group internal_energy_bg           
            
            
            
            %field_type group internal_energy_pert
            sgid = H5G.create(gid,'/field_types/internal_energy_pert',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,23);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','PerturbedInternalEnergy')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,11);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{Pa}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group internal_energy_pert         
            
             %field_type group mag_field_x_bg
            sgid = H5G.create(gid,'/field_types/mag_field_x_bg',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,35);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','xComponentofBackgroundMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_x_bg
            
              %field_type group mag_field_x_pert
            sgid = H5G.create(gid,'/field_types/mag_field_x_pert',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,34);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','xComponentofPerturbedMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_x_pert           
 
            
            
            
            
               %field_type group mag_field_y_bg
            sgid = H5G.create(gid,'/field_types/mag_field_y_bg',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,35);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','yComponentofBackgroundMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_y_bg
            
              %field_type group mag_field_y_pert
            sgid = H5G.create(gid,'/field_types/mag_field_y_pert',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,34);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','yComponentofPerturbedMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_y_pert           
          
            
            
            
            
            
            
            %field_type group mag_field_z_bg
            sgid = H5G.create(gid,'/field_types/mag_field_z_bg',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,35);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','zComponentofBackgroundMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_z_bg
            
              %field_type group mag_field_z_pert
            sgid = H5G.create(gid,'/field_types/mag_field_z_pert',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,34);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','zComponentofPerturbedMagneticField')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',10000.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,10);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{T}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group mag_field_z_pert           

            
            
 
              %field_type group velocity_x
            sgid = H5G.create(gid,'/field_types/velocity_x',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','xComponentofVelocity')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',100.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{\frac{m}{s}}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group velocity_x           
            
               %field_type group velocity_y
            sgid = H5G.create(gid,'/field_types/velocity_y',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','yComponentofVelocity')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',100.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{\frac{m}{s}}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group velocity_y            
            
            
                %field_type group velocity_z
            sgid = H5G.create(gid,'/field_types/velocity_z',plist,plist,plist);
            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            %H5T.set_size(type_id,'H5T_VARIABLE');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_name',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','zComponentofVelocity')
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_DOUBLE');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_to_cgs',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',100.0);
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_C_S1');
            H5T.set_size(type_id,20);
            H5T.set_strpad(type_id,'H5T_STR_NULLTERM');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'field_units',type_id,space_id,acpl);
            H5A.write(attr_id,'H5ML_DEFAULT','\mathrm{\frac{m}{s}}');
            H5A.close(attr_id);
            H5T.close(type_id);

            acpl_id = H5P.create('H5P_ATTRIBUTE_CREATE');
            type_id = H5T.copy('H5T_NATIVE_INT64');
            space_id = H5S.create('H5S_SCALAR');
            attr_id = H5A.create(sgid,'staggering',type_id,space_id,acpl_id);
            H5A.write(attr_id,'H5ML_DEFAULT',0);
            H5A.close(attr_id);
            H5T.close(type_id);

            H5G.close(sgid);
            %end of field_type group velocity_z           
            
            
            
            

            H5G.close(gid);







            H5F.close(fid);


            
          end
        
        
        
        
        function  griddim=getgriddimensions(obj)
           griddim=obj.grid_dimensions; 
        end    
        function newobj=read_gridinfo_h5( obj, filename)
            
            newobj=sim_gridinfo;
            
            newobj.grid_dimensions=h5read(filename,'/grid_dimensions');
            newobj.grid_left_index=h5read(filename,'/grid_left_index');
            %newobj.grid_right_index=h5read(filename,'/grid_right_index');
            newobj.grid_level=h5read(filename,'/grid_level');
            newobj.grid_parent_id=h5read(filename,'/grid_parent_id');
            newobj.grid_particle_count=h5read(filename,'/grid_particle_count');
            
             newobj.data_software=h5readatt(filename,'/gridded_data_format','data_software');
            newobj.data_software_version=h5readatt(filename,'/gridded_data_format','data_software_version');
           
            
        end  
        
        
        function write_gridinfo_h5( obj, filename)
            
            
            
            h5write(filename,'/grid_dimensions',obj.grid_dimensions);
            h5write(filename,'/grid_left_index',obj.grid_left_index);
            %newobj.grid_right_index=h5read(filename,'/grid_right_index',);
            %h5write(filename,'/grid_level',obj.grid_level);
            %h5write(filename,'/grid_parent_id',obj.grid_parent_id);
            %h5write(filename,'/grid_particle_count',obj.grid_particle_count);
            
            h5writeatt(filename,'/gridded_data_format','data_software',obj.data_software);
            h5writeatt(filename,'/gridded_data_format','data_software_version',obj.data_software_version);
  
            %h5writeatt(filename,'/field_types/density_bg','field_name','BackgroundDensity');
           

            
        end 
        
  
               
        
        
        
        
    end
    
end

